project 'EpitechEisenhower.xcodeproj'
platform :ios, '10.0'
use_frameworks!

target 'EpitechEisenhower' do
    pod 'Alamofire', '~> 4.7'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'RxSwift'
    pod 'RxCocoa'
end
